baseURL = "http://example.org/"
languageCode = "en-us"
theme = "kotkt"
defaultContentLanguage = "en"

[languages]
[languages.en]
title = "The Knights"
weight = 1
[languages.nl]
title = "De Knights"
weight = 2
