name: Deploy site
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Download website
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site
      - name: Upload website
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SOURCE: site
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
